# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-23 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomapp', '0004_auto_20190122_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='\u041e\u0431\u0449\u0430\u044f \u0441\u0443\u043c\u043c\u0430')),
                ('first_name', models.CharField(max_length=200, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=200, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('phone', models.CharField(max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('addres', models.CharField(max_length=255, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('buying_type', models.CharField(choices=[('\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437', '\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437'), ('\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430', '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430')], max_length=40, verbose_name='\u0422\u0438\u043f \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('comments', models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438')),
                ('status', models.CharField(choices=[('\u041f\u0440\u0438\u043d\u044f\u0442 \u0432 \u043e\u0431\u0440\u043e\u0431\u043e\u0442\u043a\u0443', '\u041f\u0440\u0438\u043d\u044f\u0442 \u0432 \u043e\u0431\u0440\u043e\u0431\u043e\u0442\u043a\u0443'), ('\u0412\u044b\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f', '\u0412\u044b\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f'), ('\u041e\u043f\u043b\u0430\u0447\u0435\u043d', '\u041e\u043f\u043b\u0430\u0447\u0435\u043d')], max_length=100, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='ecomapp.CartItem'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='ecomapp.Cart', verbose_name='\u0422\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
    ]
