# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_auto_20190124_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Cart', verbose_name='\u0422\u043e\u0432\u0430\u0440\u044b'),
            preserve_default=False,
        ),
    ]
