# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_auto_20190131_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'price', '-price'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
