# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_auto_20190523_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='brand',
            new_name='author',
        ),
    ]
