# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_auto_20190523_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
    ]
